apiVersion: apps/v1
kind: Deployment

metadata:
  name: eks-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: eks-backend

  template:
    metadata:
      labels:
        app: eks-backend

    spec:
      containers:
        - name: eks-backend
          image: 144999876473.dkr.ecr.us-east-1.amazonaws.com/eks-backend:latest

          ports:
            - containerPort: 3000