apiVersion: apps/v1
kind: Deployment

metadata:
  name: eks-frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: eks-frontend

  template:
    metadata:
      labels:
        app: eks-frontend

    spec:
      containers:
        - name: eks-frontend
          image: 144999876473.dkr.ecr.us-east-1.amazonaws.com/eks-frontend:latest

          ports:
            - containerPort: 80