name: deploy-eks

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: eks-demo
  ECR_URI: 144999876473.dkr.ecr.us-east-1.amazonaws.com/eks-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t eks-demo .

      - name: Tag Docker image
        run: |
          docker tag eks-demo:latest $ECR_URI:latest

      - name: Push Docker image
        run: |
          docker push $ECR_URI:latest

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $CLUSTER_NAME

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/

      - name: Restart Kubernetes deployment
        run: |
          kubectl rollout restart deployment eks-demo