name: deploy-eks

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: eks-demo

  ECR_BACKEND_URI: 144999876473.dkr.ecr.us-east-1.amazonaws.com/eks-backend
  ECR_FRONTEND_URI: 144999876473.dkr.ecr.us-east-1.amazonaws.com/eks-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # =========================
      # BACKEND
      # =========================

      - name: Build backend image
        run: |
          docker build \
            -t eks-backend \
            ./backend

      - name: Tag backend image
        run: |
          docker tag eks-backend:latest \
            $ECR_BACKEND_URI:latest

      - name: Push backend image
        run: |
          docker push $ECR_BACKEND_URI:latest

      # =========================
      # FRONTEND
      # =========================

      - name: Build frontend image
        run: |
          docker build \
            -t eks-frontend \
            ./frontend

      - name: Tag frontend image
        run: |
          docker tag eks-frontend:latest \
            $ECR_FRONTEND_URI:latest

      - name: Push frontend image
        run: |
          docker push $ECR_FRONTEND_URI:latest

      # =========================
      # CONNECT TO EKS
      # =========================

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $CLUSTER_NAME

      # =========================
      # APPLY K8S
      # =========================

      - name: Apply backend manifests
        run: |
          kubectl apply -f k8s/backend/

      - name: Apply frontend manifests
        run: |
          kubectl apply -f k8s/frontend/

      # =========================
      # RESTART DEPLOYMENTS
      # =========================

      - name: Restart backend deployment
        run: |
          kubectl rollout restart deployment eks-backend

      - name: Restart frontend deployment
        run: |
          kubectl rollout restart deployment eks-frontend